### ISSUE TITLE
2.0 breaks re-enabling javascript, had to uninstall

### ISSUE THREAD

**Issue by stickfigure** [maximelebreton/quick-javascript-switcher#72]
Just got auto-updated to v2.0.0 and to say it's a big disappointment is an understatement. Turning javascript back on doesn't work. The only way to get JS back on for a website is to uninstall the extension.

**Comment by maximelebreton** [comment]
Hello @stickfigure, and thanks for the report.
To help me to find the problem, can you provide me more information, and the Chrome version you use?

The best way to help me is to send me screens of these pages (if there is no privacy informations):
- QJS options: [chrome://extensions/?options=hjakodbnficanceefobnjkfiffkhgjcg](chrome://extensions/?options=hjakodbnficanceefobnjkfiffkhgjcg)
- Chrome Javscript content settings: [chrome://settings/content/javascript](chrome://settings/content/javascript)

I already fix a bug reported by someone else, and maybe it will fix yours, with version 2.0.1 (available on the Chrome webstore)

If not, it's a possible conflict with previous version rules, so you can try to reset QJS rules by right click on the extension icon > `More...` > `Danger zone` > `Clear all rules`

![image](https://github.com/user-attachments/assets/a902df96-9b9e-48db-b1b7-445e4874a221)

Thanks in advance for the investigation

**Comment by Graywaren** [comment]
I am also having this issue, along with at least one website where it fails to turn off js all together.. When it fails to turn JS back on i need to go into the right click menu > domain/subdomain > allow domain again. For websites it wouldn't turn off, I've had to use Pause JS no refresh and the toggle never changes. I at first thought the toggle was broken, but tested it on github and the toggle went red like it should, but then I couldn't turn it back off. The toggle is also much too difficult to see, but I'll make a separate post about that.

Clearing all rules did not fix the issue. I am using 2.0.1.

Here are my versions of the requested screen shots

Here's the options, this is after I cleared all rules, so I'm not sure where all those rules are coming from? There are many more out of frame.
![qjs1](https://github.com/user-attachments/assets/3670bdbc-5e7b-4200-9093-9face3cb1574)

Rest of the settings/options, not sure if you needed these
![qjs2](https://github.com/user-attachments/assets/179ef8e2-d607-4b1b-a51e-d76b6ca9c72f)
![qjs3](https://github.com/user-attachments/assets/a3c71f41-785e-4cfe-9228-e50454131b5c)

Here's the chrome javascript settings, as you can see those three websites are the ones I had to use allow js on those sites to get QJS to allow javascript again... 
![qjs4](https://github.com/user-attachments/assets/de5d665f-ae58-41a8-93a6-d4ba1f2df14e)

**Comment by dlatx** [comment]
I was having the same issue. Tried disabling and reenabling, ands also tried going to more -> danger zone -> clear all rules, and was still unable to turn JS back on for sites where it was disabled. I completely uninstalled the extension, reinstalled, and now it works. So while the new version works, it seems like there is an issue when upgrading.

Using Macos 14.5, Chrome Version 129.0.6668.101 and Quick Javascript Switch 2.0.1

**Comment by nicolasnoble** [comment]
I didn't have to clear the rules, but I had to uninstall / reinstall the extension to make it work again. The toggle button just wouldn't work anymore.

**Comment by nicolasnoble** [comment]
Okay, the extension broke again shortly after for me, when I re-disabled javascript by default on all websites. Basically, this:

![image](https://github.com/user-attachments/assets/6501e085-f208-473e-b119-642d4113eed7)

This makes the extension fairly useless in its current state if the problem persists this way, because I want javascript disabled by default on all websites, and only allow it on select domains using the extension, not the other way around.

**Comment by jackytsa** [comment]
Same issue. I would say this is a self-destruct update, it was once the best toggle. Now I'm uninstalling and looking for an alternative.

**Comment by maximelebreton** [comment]
Okay, thanks for these reports, for now I don't understand these unwanted behaviours but I'm on the way to fix this.

**Comment by maximelebreton** [comment]
Hello there, I just push a 2.0.2 version on the Chrome webstore.
I think i've found the bug.

On the new 2.0 version, I tried to introduce a new behaviour (clear the rule) to prevent storing `allow` rules in a globally allowed js context (and `block` rules in a globally blocked context), but it seems that causes many conflicts if there is existing rules, so I've fallback to the classic behaviour (store everything, like in the v1), and hope that will fix the problem.

Can you test it and keep me informed?

Thanks!

**Comment by gummykage** [comment]
Btw this fixed the problem for me. Clear all rules. Now the toggle works as intended and actually turns red and green.

**Comment by nicolasnoble** [comment]
I can confirm that version 2.0.2 now works when javascript is disabled by default. Thanks.

**Comment by pageaffairs** [comment]
@maximelebreton — I commented on this in the Web Store but it doesn't allow for follow-up comments, so I just wanted to say here also that 2.0.2 fixed it for me. This little mishap has made me realize how addicted I am to this addon and that I should really show my appreciation by sending you some money, so I'm going to attempt that now! Thanks again. Great work!

**Comment by Graywaren** [comment]
So far seems to be working for me as well! Thanks for the quick fix!

**Comment by nicolasnoble** [comment]
So, I am coming back to this. While the problem is gone for me for *most* websites, anything that's local, like http://127.0.0.1, or https://10.12.14.16 exhibits the same problem: the toggle will stay low even when clicking on it.

**Comment by maximelebreton** [comment]
Hello, and thanks for this report, i'll fix it in the next minor version who will come in few days, I'll notify you here.

**Comment by maximelebreton** [comment]
I've just released a `2.1.0` version on the Chrome Webstore.

@nicolasnoble can you confirm it solves the problem with ip addresses?

Thanks

**Comment by Almenon** [comment]
I had the same problem with 2.0.2. I went to chrome://extensions/ and clicked on `update` which updated it to `2.1.0`. After I updated I restarted Chrome. Now I have a a couple new problems:

1. On Github when I left click on the switcher, the icon does not change. When I reload the page javascript is disabled but the button is still in the on position.
2. On https://cooking.nytimes.com/topics/dinner-recipes, when I click on the switcher, nothing happens. When I reload, javascript is still enabled. When I go to the switcher settings with the list of domains and try to remove the allow for `https://cooking.nytimes.com/*`, nothing happens.

<details><summary>Console logs for 1. when I first click on the switcher:</summary>

```
background.js:22 Invalid url!
u @ background.js:22
(anonymous) @ background.js:29
l @ background.js:29
await in l
c @ background.js:1
a @ background.js:1
(anonymous) @ background.js:1Understand this errorAI
background.js:22 Uncaught (in promise) Error: Invalid url!
    at u (background.js:22:13932)
    at background.js:29:13998
    at Array.reduce (<anonymous>)
    at l (background.js:29:13920)
    at async c (background.js:1:17852)
    at async a (background.js:1:18178)
    at async background.js:1:6916
u @ background.js:22
(anonymous) @ background.js:29
l @ background.js:29Understand this errorAI
background.js:22 0 'SUBDOMAIN ???????????????'
background.js:22 TOGGLE DOMAIN
background.js:22 *://*.github.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 true 'IS SAME ??????????????'
background.js:22 try to remove http://*.github.com/* !!!!!!!!!!!!!!!!!!
background.js:22 http://*.github.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]0: {primaryPattern: CENSORED: Array(0) 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove https://*.github.com/* !!!!!!!!!!!!!!!!!!
background.js:22 https://*.github.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove *://*.github.com/* !!!!!!!!!!!!!!!!!!
background.js:22 *://*.github.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 {…} 'chrome.contentSettings'
background.js:22 block *://*.github.com/* rule added to content settings
background.js:29 block *://*.github.com/* rule added to storage
background.js:22 toggle from allow to block: *://*.github.com/*
background.js:22 Invalid url!
u @ background.js:22
(anonymous) @ background.js:29
l @ background.js:29
await in l
c @ background.js:1
a @ background.js:1
N @ background.js:22
await in N
T @ background.js:22
f @ background.js:22
await in f
u @ background.js:22
(anonymous) @ background.js:1Understand this errorAI
background.js:22 Uncaught (in promise) Error: Invalid url!
    at u (background.js:22:13932)
    at background.js:29:13998
    at Array.reduce (<anonymous>)
    at l (background.js:29:13920)
    at async c (background.js:1:17852)
    at async a (background.js:1:18178)
    at async N (background.js:22:41208)
    at async T (background.js:22:41364)
    at async f (background.js:22:38060)
    at async u (background.js:22:37648)
```
</details>

<details><summary>Console logs for 2.</summary>

```
background.js:22 Invalid url!
u @ background.js:22
(anonymous) @ background.js:29
l @ background.js:29
await in l
c @ background.js:1
a @ background.js:1
(anonymous) @ background.js:1Understand this errorAI
background.js:22 Uncaught (in promise) Error: Invalid url!
    at u (background.js:22:13932)
    at background.js:29:13998
    at Array.reduce (<anonymous>)
    at l (background.js:29:13920)
    at async c (background.js:1:17852)
    at async a (background.js:1:18178)
    at async background.js:1:6916
u @ background.js:22
(anonymous) @ background.js:29
l @ background.js:29Understand this errorAI
background.js:22 8 'SUBDOMAIN ???????????????'
background.js:22 TOGGLE SUBDOMAIN
background.js:22 *://cooking.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 true 'IS SAME ??????????????'
background.js:22 try to remove http://cooking.nytimes.com/* !!!!!!!!!!!!!!!!!!
background.js:22 http://cooking.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove https://cooking.nytimes.com/* !!!!!!!!!!!!!!!!!!
background.js:22 https://cooking.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove *://cooking.nytimes.com/* !!!!!!!!!!!!!!!!!!
background.js:22 *://cooking.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove http://*.nytimes.com/* !!!!!!!!!!!!!!!!!!
background.js:22 http://*.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove https://*.nytimes.com/* !!!!!!!!!!!!!!!!!!
background.js:22 https://*.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 try to remove *://*.nytimes.com/* !!!!!!!!!!!!!!!!!!
background.js:22 *://*.nytimes.com/* removeJavascriptRule()
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES BEFORE'
background.js:22 (84) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] 'STORAGE RULES AFTER'
background.js:22 {…} 'chrome.contentSettings'
background.js:22 block *://cooking.nytimes.com/* rule added to content settings
background.js:29 block *://cooking.nytimes.com/* rule added to storage
background.js:22 toggle from allow to block: *://cooking.nytimes.com/*
background.js:22 Invalid url!
u @ background.js:22
(anonymous) @ background.js:29
l @ background.js:29
await in l
c @ background.js:1
a @ background.js:1
N @ background.js:22
await in N
L @ background.js:22
f @ background.js:22
await in f
u @ background.js:22
(anonymous) @ background.js:1Understand this errorAI
background.js:22 Uncaught (in promise) Error: Invalid url!
    at u (background.js:22:13932)
    at background.js:29:13998
    at Array.reduce (<anonymous>)
    at l (background.js:29:13920)
    at async c (background.js:1:17852)
    at async a (background.js:1:18178)
    at async N (background.js:22:41208)
    at async L (background.js:22:41294)
    at async f (background.js:22:38018)
    at async u (background.js:22:37648)
```
</details>

Let me know if you want to hop on a call, I'm in PST timezone

P.S. Great extension, I donated :)

**Comment by nicolasnoble** [comment]
Upgraded to 2.1.0, but raw IP addresses still won't work properly.

I'm not sure how to debug this - any hints? I've never really looked at Chrome extension development.

**Comment by maximelebreton** [comment]
> Upgraded to 2.1.0, but raw IP addresses still won't work properly.
> 
> I'm not sure how to debug this - any hints? I've never really looked at Chrome extension development.

@nicolasnoble can you provide me the ip address with the problem? Or if private, the format.

The ip address should work, but maybe I miss something:
https://github.com/maximelebreton/quick-javascript-switcher/blob/4adc680c738a79429c5948f22b73d4052995e44c/tests/unit/example.spec.ts#L146-L151

**Comment by maximelebreton** [comment]
@Almenon I tested https://cooking.nytimes.com/topics/dinner-recipes and github.com on my computer and it's working fine, so for now I don't understand.

Can you provide me a screenshot of :
- QJS options: chrome://extensions/?options=hjakodbnficanceefobnjkfiffkhgjcg
- Chrome Javscript content settings: chrome://settings/content/javascript

Thanks for your help!

**Comment by nicolasnoble** [comment]
> @nicolasnoble can you provide me the ip address with the problem? Or if private, the format.
> 
> The ip address should work, but maybe I miss something:
> 
> https://github.com/maximelebreton/quick-javascript-switcher/blob/4adc680c738a79429c5948f22b73d4052995e44c/tests/unit/example.spec.ts#L146-L151

This was when hitting a private internal machine, with the url being `http://10.12.1.2:3000/auth`

**Comment by Almenon** [comment]
QJS options: https://imgur.com/OFxGgsJ
Chrome Javascript content settings: https://imgur.com/kVrtNW4

**Comment by maximelebreton** [comment]
Thanks @Almenon, it was very helpful.
I just released a `2.2.0` version to the Chrome Webstore and it should fix (I hope) your problem.

And thanks @nicolasnoble, with `2.2.0` version the external ip addresses with specified **port** should work now.

Can you confirm?

**Comment by Almenon** [comment]
It works now :) but the icon is still stuck in the upright position

![image](https://github.com/user-attachments/assets/8c56a94d-07b6-475f-868c-2b689c7ea2fe)
![image](https://github.com/user-attachments/assets/5f5fbae7-ebd4-4003-977e-21f22ab02588)

**Comment by devtemp0** [comment]
This problem has bricked Chrome entirely for me.  Uninstalling the extension has set the global JavaScript setting as "Not allowed (default)" and blocked the ability to change the global setting to allow "Sites can use JavaScript". (The setting can be selected, but does not work.)

Because it has globally disabled JavaScript I cannot even re-install the extension. No js dependent sites can be used. The browser has been made useless.

Any fix available?

![Image](https://github.com/user-attachments/assets/fa5520f6-dc10-4e67-9b6d-90edbecdf6d4)

**Comment by maximelebreton** [comment]
Hi @devtemp0,
QJS only applies JavaScript rules on a per-site basis. There is no code in the extension that disables JavaScript globally.

So maybe JavaScript has been disabled globally manually by accident, or by another extension if you’ve tested several JS-related ones?

___

To check and reset the chrome JavaScript global settings, go to this url:
`chrome://settings/content/javascript`
and make sure “Sites can use JavaScript” is enabled (not the opposite).

<img width="497" height="324" alt="Image" src="https://github.com/user-attachments/assets/25d4692a-0137-4a9d-9155-ebb25e3142d1" />  

___

If this doesn’t change anything, the Chrome Web Store itself may be blocked by a specific QJS rule. In that case, you’ll need to clear all rules created by QJS.
To clear QJS rules, open the QJS options contextual menu (right click), and go to More > Danger Zone > Clear all rules:

<img width="467" height="410" alt="Image" src="https://github.com/user-attachments/assets/4afda45f-2992-4658-a469-b473896db86a" />

___

If you’re unable to reinstall QJS from the Chrome Web Store, you can install it directly via the .crx file:
https://clients2.google.com/service/update2/crx?response=redirect&prodversion=130.0.0.0&acceptformat=crx2,crx3&x=id%3Dgeddoclleiomckbhadiaipdggiiccfje%26uc

Hope that's help!
